name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "package.json"
      - "package-lock.json"
      - "script/coin-price-data-fetcher/package.json"
      - "script/coin-price-data-fetcher/package-lock.json"
      - ".github/workflows/**"
      - "Dockerfile"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Dependency review
        uses: actions/dependency-review-action@v4
