name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "package.json"
      - "package-lock.json"
      - "src/**"
      - "test/**"
      - "script/**"
      - "tsconfig*.json"
      - ".nvmrc"
      - ".npmrc"
      - "script/coin-price-data-fetcher/.npmrc"
      - ".github/workflows/**"
      - "Dockerfile"
      - ".dockerignore"
  pull_request_review:
    types: [submitted]

permissions:
  contents: read

jobs:
  lint:
    if: >-
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review' &&
        (github.event.review.state == 'approved' || contains(github.event.review.body, '/check')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            script/coin-price-data-fetcher/package-lock.json
      - name: install
        run: |
          npm ci
      - name: run eslint
        run: |
          npm run eslint
  prettier:
    if: >-
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review' &&
        (github.event.review.state == 'approved' || contains(github.event.review.body, '/check')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            script/coin-price-data-fetcher/package-lock.json
      - name: install
        run: |
          npm ci
      - name: run prettier
        run: |
          npx prettier --check src
  build:
    if: >-
      github.event_name == 'pull_request' ||
      (github.event_name == 'pull_request_review' &&
        (github.event.review.state == 'approved' || contains(github.event.review.body, '/check')))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: |
            package-lock.json
            script/coin-price-data-fetcher/package-lock.json
      - name: install
        run: |
          npm ci
      - name: run build
        run: |
          npm run build
      - name: build Docker image
        run: |
          docker build -t yoroi-graphql-migration-backend:ci .
